/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // สร้าง Sidebar อัตโนมัติตามไฟล์ที่มีอยู่ในโฟลเดอร์ docs
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;